### ISSUE TITLE
Exception after upgrade to 1.0.0

### ISSUE THREAD

**Issue by soupdiver** [jenkinsci/hipchat-plugin#63]
I upgraded from version `0.1.9` to latest `1.0.0` and stuff stopped working :/
I can send a test notification from the Jenkins settings menu but my jobs fail with the following stack trace

```
FATAL: hudson/tasks/test/AbstractTestResultAction
java.lang.NoClassDefFoundError: hudson/tasks/test/AbstractTestResultAction
    at jenkins.plugins.hipchat.utils.BuildUtils.getTestData(BuildUtils.java:118)
    at jenkins.plugins.hipchat.utils.BuildUtils.collectParametersFor(BuildUtils.java:49)
    at jenkins.plugins.hipchat.model.NotificationType.getMessage(NotificationType.java:89)
    at jenkins.plugins.hipchat.model.NotificationType.getMessage(NotificationType.java:84)
    at jenkins.plugins.hipchat.HipChatNotifier.publishNotificationIfEnabled(HipChatNotifier.java:257)
    at jenkins.plugins.hipchat.HipChatNotifier.prebuild(HipChatNotifier.java:216)
    at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:840)
    at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:835)
    at hudson.model.Build$BuildExecution.doRun(Build.java:144)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
    at hudson.model.Run.execute(Run.java:1741)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:408)
```

My Jenkins version: `1.625.3`

**Comment by aldaris** [comment]
That sounds very strange. The plugin depends on the junit plugin now. Do you have that installed? Which version?

**Comment by soupdiver** [comment]
ok after updating JUint plugin stuff seems to work now :)

**Comment by aldaris** [comment]
Which version did you have that didn't work?

**Comment by soupdiver** [comment]
It was `1.5` now `1.10`

**Comment by aldaris** [comment]
As the plugin currently depends on 1.3, I need to make sure that the plugin is actually able to work with that big range of the junit plugin. I think I'll need to adjust the plugin version..

**Comment by soupdiver** [comment]
Ah okay.
Yeah unfortunately I'm not sure if the plugin was disabled or if the version was the problem :/

**Comment by saz** [comment]
We're having the same issue.

Plugin version: 1.0.0
Jenkins version: 1.652
JUnit plugin version: 1.11

JUnit is enabled. Restarting Jenkins won't fix this error.

```
FATAL: hudson/tasks/test/AbstractTestResultAction
java.lang.NoClassDefFoundError: hudson/tasks/test/AbstractTestResultAction
	at jenkins.plugins.hipchat.utils.BuildUtils.getTestData(BuildUtils.java:118)
	at jenkins.plugins.hipchat.utils.BuildUtils.collectParametersFor(BuildUtils.java:49)
	at jenkins.plugins.hipchat.model.NotificationType.getMessage(NotificationType.java:89)
	at jenkins.plugins.hipchat.model.NotificationType.getMessage(NotificationType.java:84)
	at jenkins.plugins.hipchat.HipChatNotifier.publishNotificationIfEnabled(HipChatNotifier.java:257)
	at jenkins.plugins.hipchat.HipChatNotifier.prebuild(HipChatNotifier.java:216)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:837)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:832)
	at hudson.model.Build$BuildExecution.doRun(Build.java:144)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: java.lang.ClassNotFoundException: hudson.tasks.test.AbstractTestResultAction
	at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
	at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
	at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 14 more
```

**Comment by aldaris** [comment]
@saz Not sure why this happens for you. The class looks to be present in 1.11 version as well. Could it be that you have an older version of the junit plugin lurking around on your classpath?

**Comment by nan008** [comment]
We have the same problem

Anyone has a solution? For us the only thing working is to downgrade the hipchat pluigin to 0.1.9

Plugin version: 1.0.0
Jenkins version: 1.653
JUnit plugin version: 1.11

**Comment by aldaris** [comment]
Probably there is an old junit plugin version lurking around on your classpath. What do you have matching .jenkins/plugins/junit* ?

Alternatively it may be beneficial to enable [verbose class loading](http://www.oracle.com/technetwork/java/javase/clopts-139448.html#gbmtm) and see where AbstractTestResultAction is coming from.

**Comment by aldaris** [comment]
I'm still unable to reproduce this issue, closing.
